# Generated by Django 6.0.3 on 2026-03-29 05:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('rule_type', models.CharField(choices=[('ELIGIBILITY', 'Eligibility'), ('PREMIUM', 'Premium'), ('CLAIM', 'Claim')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.PositiveIntegerField(default=1)),
                ('condition_field', models.CharField(max_length=100)),
                ('operator', models.CharField(max_length=20)),
                ('condition_value', models.CharField(max_length=255)),
                ('action_type', models.CharField(max_length=50)),
                ('action_value', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['priority'],
            },
        ),
    ]
